name: Build/Push Profile API image to Docker Hub
on:
  push:
    branches:
      - develop
jobs:
  build-and-push-docker-image:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
    - name: Build and push docker image
      uses: actions/checkout@master
    - run: |
        export TAG=$(cat VERSION)
        docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
        docker build -t udomiljubimca/profile-api:$TAG .
        docker push udomiljubimca/profile-api:$TAG